export const fonts = [
  { label: "Albert Sans", value: "Albert Sans", category: "sans-serif" },
  { label: "Alegreya", value: "Alegreya", category: "serif" },
  { label: "Alegreya Sans", value: "Alegreya Sans", category: "sans-serif" },
  { label: "Alice", value: "Alice", category: "serif" },
  { label: "Amatic SC", value: "Amatic SC", category: "display" },
  { label: "Amiri", value: "Amiri", category: "serif" },
  { label: "Anonymous Pro", value: "Anonymous Pro", category: "monospace" },
  { label: "Anton", value: "Anton", category: "display" },
  { label: "Archivo", value: "Archivo", category: "sans-serif" },
  { label: "Archivo Narrow", value: "Archivo Narrow", category: "sans-serif" },
  { label: "Arimo", value: "Arimo", category: "sans-serif" },
  { label: "Asap", value: "Asap", category: "sans-serif" },
  { label: "Asap Condensed", value: "Asap Condensed", category: "sans-serif" },
  {
    label: "Atkinson Hyperlegible",
    value: "Atkinson Hyperlegible",
    category: "sans-serif",
  },
  { label: "Baloo 2", value: "Baloo 2", category: "display" },
  { label: "Baloo Bhaijaan 2", value: "Baloo Bhaijaan 2", category: "display" },
  { label: "Barlow", value: "Barlow", category: "sans-serif" },
  {
    label: "Barlow Condensed",
    value: "Barlow Condensed",
    category: "sans-serif",
  },
  { label: "Bebas Neue", value: "Bebas Neue", category: "display" },
  {
    label: "Berkshire Swash",
    value: "Berkshire Swash",
    category: "handwriting",
  },
  { label: "BioRhyme", value: "BioRhyme", category: "serif" },
  { label: "Birthstone", value: "Birthstone", category: "script" },
  { label: "Bitter", value: "Bitter", category: "serif" },
  { label: "Blaka", value: "Blaka", category: "display" },
  { label: "Bodoni Moda", value: "Bodoni Moda", category: "serif" },
  { label: "Bungee", value: "Bungee", category: "display" },
  { label: "Bungee Inline", value: "Bungee Inline", category: "display" },
  { label: "Bungee Shade", value: "Bungee Shade", category: "display" },
  { label: "Cabin", value: "Cabin", category: "sans-serif" },
  { label: "Cairo", value: "Cairo", category: "sans-serif" },
  { label: "Caprasimo", value: "Caprasimo", category: "display" },
  { label: "Cardo", value: "Cardo", category: "serif" },
  { label: "Carter One", value: "Carter One", category: "display" },
  { label: "Catamaran", value: "Catamaran", category: "sans-serif" },
  { label: "Caveat", value: "Caveat", category: "handwriting" },
  { label: "Ceviche One", value: "Ceviche One", category: "display" },
  { label: "Charmonman", value: "Charmonman", category: "handwriting" },
  { label: "Chivo", value: "Chivo", category: "sans-serif" },
  { label: "Cinzel", value: "Cinzel", category: "serif" },
  { label: "Comfortaa", value: "Comfortaa", category: "sans-serif" },
  { label: "Cormorant", value: "Cormorant", category: "serif" },
  {
    label: "Cormorant Garamond",
    value: "Cormorant Garamond",
    category: "serif",
  },
  { label: "Cormorant Infant", value: "Cormorant Infant", category: "serif" },
  { label: "Cormorant Upright", value: "Cormorant Upright", category: "serif" },
  { label: "Courgette", value: "Courgette", category: "handwriting" },
  { label: "Cousine", value: "Cousine", category: "monospace" },
  {
    label: "Covered By Your Grace",
    value: "Covered By Your Grace",
    category: "handwriting",
  },
  { label: "Dancing Script", value: "Dancing Script", category: "handwriting" },
  { label: "DM Sans", value: "DM Sans", category: "sans-serif" },
  { label: "DM Serif Display", value: "DM Serif Display", category: "serif" },
  { label: "DM Serif Text", value: "DM Serif Text", category: "serif" },
  { label: "EB Garamond", value: "EB Garamond", category: "serif" },
  { label: "Eczar", value: "Eczar", category: "serif" },
  { label: "Epilogue", value: "Epilogue", category: "sans-serif" },
  { label: "Expletus Sans", value: "Expletus Sans", category: "display" },
  { label: "Fanwood Text", value: "Fanwood Text", category: "serif" },
  { label: "Faster One", value: "Faster One", category: "display" },
  { label: "Fira Code", value: "Fira Code", category: "monospace" },
  { label: "Fira Sans", value: "Fira Sans", category: "sans-serif" },
  { label: "Fjalla One", value: "Fjalla One", category: "sans-serif" },
  { label: "Fraunces", value: "Fraunces", category: "serif" },
  { label: "Freckle Face", value: "Freckle Face", category: "display" },
  { label: "Ga Maamli", value: "Ga Maamli", category: "display" },
  { label: "Gentium Plus", value: "Gentium Plus", category: "serif" },
  {
    label: "Gloria Hallelujah",
    value: "Gloria Hallelujah",
    category: "handwriting",
  },
  { label: "Gotu", value: "Gotu", category: "serif" },
  { label: "Heebo", value: "Heebo", category: "sans-serif" },
  { label: "IBM Plex Mono", value: "IBM Plex Mono", category: "monospace" },
  { label: "IBM Plex Sans", value: "IBM Plex Sans", category: "sans-serif" },
  { label: "IBM Plex Serif", value: "IBM Plex Serif", category: "serif" },
  { label: "Inconsolata", value: "Inconsolata", category: "monospace" },
  { label: "Indie Flower", value: "Indie Flower", category: "handwriting" },
  {
    label: "Instrument Sans",
    value: "Instrument Sans",
    category: "sans-serif",
  },

  { label: "Instrument Serif", value: "Instrument Serif", category: "serif" },
  { label: "Inter", value: "Inter", category: "sans-serif" },
  { label: "JetBrains Mono", value: "JetBrains Mono", category: "monospace" },
  { label: "Josefin Sans", value: "Josefin Sans", category: "sans-serif" },
  { label: "Josefin Slab", value: "Josefin Slab", category: "serif" },
  { label: "Jost", value: "Jost", category: "sans-serif" },
  { label: "Julee", value: "Julee", category: "handwriting" },
  { label: "Karla", value: "Karla", category: "sans-serif" },
  { label: "Kenia", value: "Kenia", category: "display" },
  { label: "Lato", value: "Lato", category: "sans-serif" },
  { label: "Lexend", value: "Lexend", category: "sans-serif" },
  { label: "Libre Baskerville", value: "Libre Baskerville", category: "serif" },
  { label: "Libre Franklin", value: "Libre Franklin", category: "sans-serif" },
  { label: "Lobster", value: "Lobster", category: "display" },
  { label: "Lora", value: "Lora", category: "serif" },
  { label: "Lustria", value: "Lustria", category: "serif" },
  //
  {
    label: "M PLUS Rounded 1c",
    value: "M PLUS Rounded 1c",
    category: "sans-serif",
  },
  { label: "Manrope", value: "Manrope", category: "sans-serif" },
  { label: "Marcellus", value: "Marcellus", category: "serif" },
  { label: "Markazi Text", value: "Markazi Text", category: "serif" },
  { label: "Merienda", value: "Merienda", category: "handwriting" },
  { label: "Merriweather", value: "Merriweather", category: "serif" },
  {
    label: "Merriweather Sans",
    value: "Merriweather Sans",
    category: "sans-serif",
  },
  { label: "Milonga", value: "Milonga", category: "display" },
  { label: "Modak", value: "Modak", category: "display" },
  { label: "Monoton", value: "Monoton", category: "display" },
  { label: "Montserrat", value: "Montserrat", category: "sans-serif" },
  { label: "Mulish", value: "Mulish", category: "sans-serif" },
  { label: "Neuton", value: "Neuton", category: "serif" },
  { label: "Newsreader", value: "Newsreader", category: "serif" },
  { label: "Noto Sans", value: "Noto Sans", category: "sans-serif" },
  { label: "Noto Sans JP", value: "Noto Sans JP", category: "sans-serif" },
  { label: "Noto Serif", value: "Noto Serif", category: "serif" },
  { label: "Nunito", value: "Nunito", category: "sans-serif" },
  { label: "Oi", value: "Oi", category: "serif" },
  { label: "Old Standard TT", value: "Old Standard TT", category: "serif" },
  { label: "Open Sans", value: "Open Sans", category: "sans-serif" },
  { label: "Orbitron", value: "Orbitron", category: "sans-serif" },
  { label: "Oswald", value: "Oswald", category: "sans-serif" },
  { label: "Outfit", value: "Outfit", category: "sans-serif" },
  { label: "Pacifico", value: "Pacifico", category: "handwriting" },
  {
    label: "Pathway Gothic One",
    value: "Pathway Gothic One",
    category: "sans-serif",
  },
  { label: "Patua One", value: "Patua One", category: "display" },
  { label: "Pencerio", value: "Pencerio", category: "handwriting" },
  {
    label: "Permanent Marker",
    value: "Permanent Marker",
    category: "handwriting",
  },
  { label: "Piazzolla", value: "Piazzolla", category: "serif" },
  { label: "Pinyon Script", value: "Pinyon Script", category: "script" },
  { label: "Playfair Display", value: "Playfair Display", category: "serif" },
  { label: "Playwrite TZ", value: "Playwrite TZ", category: "serif" },
  { label: "Playwrite US Trad", value: "Playwrite US Trad", category: "serif" },
  //
  {
    label: "Plus Jakarta Sans",
    value: "Plus Jakarta Sans",
    category: "sans-serif",
  },
  { label: "Poppins", value: "Poppins", category: "sans-serif" },
  { label: "Prata", value: "Prata", category: "serif" },
  { label: "Prompt", value: "Prompt", category: "sans-serif" },
  { label: "Proza Libre", value: "Proza Libre", category: "sans-serif" },
  { label: "PT Sans", value: "PT Sans", category: "sans-serif" },
  { label: "PT Serif", value: "PT Serif", category: "serif" },
  { label: "Quattrocento", value: "Quattrocento", category: "serif" },
  {
    label: "Quattrocento Sans",
    value: "Quattrocento Sans",
    category: "sans-serif",
  },
  { label: "Quicksand", value: "Quicksand", category: "sans-serif" },
  { label: "Rajdhani", value: "Rajdhani", category: "sans-serif" },
  { label: "Raleway", value: "Raleway", category: "sans-serif" },
  { label: "Raleway Dots", value: "Raleway Dots", category: "display" },
  { label: "Righteous", value: "Righteous", category: "display" },
  { label: "Roboto", value: "Roboto", category: "sans-serif" },
  {
    label: "Roboto Condensed",
    value: "Roboto Condensed",
    category: "sans-serif",
  },
  { label: "Roboto Flex", value: "Roboto Flex", category: "sans-serif" },
  { label: "Roboto Mono", value: "Roboto Mono", category: "monospace" },
  { label: "Roboto Slab", value: "Roboto Slab", category: "serif" },
  { label: "Rosario", value: "Rosario", category: "sans-serif" },
  { label: "Rosarivo", value: "Rosarivo", category: "serif" },
  { label: "Rubik", value: "Rubik", category: "sans-serif" },
  { label: "Rubik Glitch", value: "Rubik Glitch", category: "display" },
  //
  { label: "Sacramento", value: "Sacramento", category: "handwriting" },
  { label: "Sail", value: "Sail", category: "handwriting" },
  { label: "Satisfy", value: "Satisfy", category: "script" },
  { label: "Scheherazade New", value: "Scheherazade New", category: "serif" },
  {
    label: "Shadows Into Light",
    value: "Shadows Into Light",
    category: "handwriting",
  },
  { label: "Shrikhand", value: "Shrikhand", category: "display" },
  { label: "Signika", value: "Signika", category: "sans-serif" },
  {
    label: "Signika Negative",
    value: "Signika Negative",
    category: "sans-serif",
  },
  { label: "Sometype Mono", value: "Sometype Mono", category: "monospace" },
  { label: "Sora", value: "Sora", category: "sans-serif" },
  { label: "Source Code Pro", value: "Source Code Pro", category: "monospace" },
  { label: "Source Sans 3", value: "Source Sans 3", category: "sans-serif" },
  { label: "Space Grotesk", value: "Space Grotesk", category: "sans-serif" },
  { label: "Space Mono", value: "Space Mono", category: "monospace" },
  {
    label: "Special Gothic Expanded One",
    value: "Special Gothic Expanded One",
    category: "display",
  },
  { label: "Spectral", value: "Spectral", category: "serif" },
  { label: "Spectral SC", value: "Spectral SC", category: "serif" },
  { label: "Syne", value: "Syne", category: "sans-serif" },
  { label: "Tangerine", value: "Tangerine", category: "handwriting" },
  { label: "Teko", value: "Teko", category: "sans-serif" },
  { label: "Tinos", value: "Tinos", category: "serif" },
  { label: "Ubuntu", value: "Ubuntu", category: "sans-serif" },
  { label: "Urbanist", value: "Urbanist", category: "sans-serif" },
  { label: "Varela Round", value: "Varela Round", category: "sans-serif" },
  { label: "Vesper Libre", value: "Vesper Libre", category: "serif" },
  { label: "Vollkorn", value: "Vollkorn", category: "serif" },
  {
    label: "Wix Madefor Display",
    value: "Wix Madefor Display",
    category: "sans-serif",
  },
  { label: "Work Sans", value: "Work Sans", category: "sans-serif" },
  { label: "Zilla Slab", value: "Zilla Slab", category: "serif" },
  {
    label: "Zilla Slab Highlight",
    value: "Zilla Slab Highlight",
    category: "serif",
  },
  { label: "Zodiak", value: "Zodiak", category: "display" },
];
